name: listfy_root
description: Projeto Dev Note - Todo list para desenvolvedores
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Este é um pubspec.yaml auxiliar na raiz do projeto.
# O projeto Flutter principal está na pasta 'app/'
# Para executar o aplicativo: cd app && flutter run

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true